const cat = {
  mouse: "mouse",
  key_bords: "key_bords",
  coolingPad: "coolingPad",
  headphones: "headphones",
  laptopSkinPack : "laptopSkinPack",
  smartWatches: "smartWatches",
  Shoes: "shoes",
  // robotClean: "robotClean",
  // sportWatches: "sportWatches",
  // tablets: "tablets",
  // computersAndLaptop: "computersAndLaptop",
  // camerasAndPhotos: "camerasAndPhotos",
};
export const categories = [
  {
    _id: 1001,
    name: "mouse",
    image: "https://i.postimg.cc/L8NTtg2k/hp-x500-mouse.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "mouse",
  },
  {
    _id: 1002,
    name: "Key bords",
    image: "https://i.postimg.cc/xC7pKJGp/Rainbow-Wired-Gaming-Keyboard-Mouse-GTX360.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "key_bords",
  },
  {
    _id: 1003,
    name: "Cooling Pad",
    image: "https://i.postimg.cc/CLbrqKRJ/N-99-LAPTOP-COOLING-PAD.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "coolingPad",
  },
  {
    _id: 1004,
    name: "Headphones",
    image: "https://i.postimg.cc/DZWByfVr/HEAD-SET-SY-750.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "headphones",
  },
  {
    _id: 1005,
    name: "Laptop Skin Pack",
    image: "https://i.postimg.cc/gjZS4zNz/LAPTOP-SKIN-PACK-4-IN-1-15-6.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "laptopSkinPack",
  },
  {
    _id: 1006,
    name: "Smart Watches",
    image: "https://i.postimg.cc/qR9ZRyDL/smart-watches.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "smartWatches",
  },
  {
    _id: 1007,
    name: "Shoes",
    image: "https://i.postimg.cc/637mtYcq/shoe.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "shoes",
  },
  // {
  //   _id: 1008,
  //   name: "Robot Clean",
  //   image: "https://i.ibb.co/xjpdQrr/cat-Robot-Clean.webp",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
  //   _base: "robotClean",
  // },
  // {
  //   _id: 1009,
  //   name: "Sport Watches",
  //   image: "https://i.ibb.co/HdNVLzh/cat-Sport-Watch.webp",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
  //   _base: "sportWatches",
  // },
  // {
  //   _id: 1010,
  //   name: "Tablets",
  //   image: "https://i.ibb.co/qCzTx4F/cat-Tablet.webp",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
  //   _base: "tablets",
  // },
  // {
  //   _id: 1011,
  //   name: "Computers & Laptop",
  //   image: "https://i.ibb.co/74bZ8PH/cat-Computer.webp",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
  //   _base: "computersAndLaptop",
  // },
  // {
  //   _id: 1012,
  //   name: "Cameras & Photos",
  //   image: "https://i.ibb.co/SVQVWSS/cat-Camera.webp",
  //   description:
  //     "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
  //   _base: "camerasAndPhotos",
  // },
];

export const highlightsProducts = [
  {
    _id: 3001,
    name: "New Deals at Best Prices",
    title: "From RS 500",
    buttonTitle: "Show Now",
    image: "https://i.postimg.cc/hP8MG3Y5/DELL-MS111-USB-OPTICAL-MOUSE.jpg",
    _base: "/product",
    color: "#000000",
  },
  {
    _id: 3002,
    name: "USB Mini key bord",
    title: "From RS 1400.00",
    buttonTitle: "Shop Now",
    image: "https://i.postimg.cc/sxLf16dL/c35625c85b960787fd798e7855fac157.jpg",
    _base: "/category/key_bords",
    color: "#ffffff",
  },
  {
    _id: 3003,
    name: "Wire Less mouse",
    title: "From RS1000.00",
    buttonTitle: "Shop Now",
    image: "https://i.postimg.cc/hPRpcq2m/Wireless-Mouse-Banda-G620.jpg",
    _base: "/product",
    color: "#ffffff",
  },
];

export const blogsData = [
  {
    _id: 4001,
    image: "https://i.ibb.co/XbQf5HS/blogOne.webp",
    title: "iPhone 15 rear camera design will be available",
    _base: "Technology",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  },
  {
    _id: 4002,
    image: "https://i.ibb.co/wzNpcwp/blogTwo.webp",
    title: "Setup your surround sound speaker",
    _base: "Samrt thing",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  },
  {
    _id: 4003,
    image: "https://i.ibb.co/prdZ3s8/blog-Three.webp",
    title: "Hook up a receiver for your home theater",
    _base: "Life style",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  },
];

export const products = [
  {
    _id: 2001,
    name: "hp x500 mouse",
    images: [
      "https://i.postimg.cc/L8NTtg2k/hp-x500-mouse.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 799,
    discountedPrice: 749,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "mouse",
    colors: ["black"],
    brand: "HP",
    isStock: true,
    overView: "",
    isNew: true,
    _base: cat?.mouse,
  },
  {
    _id: 2002,
    name: "DELL MS111 USB OPTICAL MOUSE",
    images: [
      "https://i.postimg.cc/hP8MG3Y5/DELL-MS111-USB-OPTICAL-MOUSE.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 549,
    discountedPrice: 499,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "mouse",
    colors: ["black"],
    brand: "mouse",
    isStock: true,
    overView: "Dell",
    isNew: true,
    _base: cat?.mouse,
  },
  {
    _id: 2003,
    name: "JEDEL 220 NORMAL MOUSE",
    images: [
      "https://i.postimg.cc/NjgD2kqf/JEDEL-220-NORMAL-MOUSE.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 399,
    discountedPrice: 399,
    quantity: 1,
    rating: 4.0,
    reviews: 50,
    category: "mouse",
    colors: ["black"],
    brand: "JEDEL",
    isStock: true,
    overView: "",
    isNew: true,
    _base: cat?.mouse,
  },
  {
    _id: 2004,
    name: "X1 GAMING MOUSE",
    images: [
      "https://i.postimg.cc/XqdLd2YX/X1-GAMING-MOUSE.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 699,
    discountedPrice: 649,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "mouse",
    colors: ["black"],
    brand: "HP",
    isStock: true,
    overView: "",
    isNew: true,
    _base: cat?.mouse,
  },
  {
    _id: 2005,
    name: "Wireless Mouse Banda (G620)",
    images: [
      "https://i.postimg.cc/hPRpcq2m/Wireless-Mouse-Banda-G620.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 999,
    discountedPrice: 949,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "mouse",
    colors: ["black"],
    brand: "G(620) Banda",
    isStock: true,
    overView: "",
    isNew: true,
    _base: cat?.mouse,
  },
  {
    _id: 2006,
    name: "14.6'' 5 in 1 LAPTOP SKIN PACK",
    images: [
      "https://i.postimg.cc/y6gb7jBM/14-6-5-in-1-LAPTOP-SKIN-PACK.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 599,
    discountedPrice: 580,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "Laptop Skin Pack",
    //colors: ["black"],
    //brand: "HP",
    isStock: true,
    overView: "",
    isNew: true,
    _base: cat?.laptopSkinPack,
  },
  {
    _id: 2007,
    name: "LAPTOP SKIN PACK 4 IN 1 15.6",
    images: [
      "https://i.postimg.cc/gjZS4zNz/LAPTOP-SKIN-PACK-4-IN-1-15-6.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 599,
    discountedPrice: 580,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "Laptop Skin Pack",
    colors: ["black"],
    brand: "HP",
    isStock: true,
    overView: "",
    isNew: true,
    _base: cat?.laptopSkinPack,
  },
  {
    _id: 2008,
    name: "Smart Watches",
    images: [
      "https://i.postimg.cc/qR9ZRyDL/smart-watches.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1299,
    discountedPrice: 1149,
    quantity: 1,
    rating: 4.8,
    reviews: 0,
    category: "Smart Watches",
    colors: ["black", "white"],
    brand: "We-Mart",
    isStock: true,
    overView: "Smart  watch",
    isNew: false,
    _base: cat?.smartWatches,
  },
  {
    _id: 2009,
    name: "HEAD SET A63 HEADSET",
    images: [
      "https://i.postimg.cc/xd16hytF/HEAD-SET-A63-HEADSET.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1599,
    discountedPrice: 0,
    quantity: 1,
    rating: 0,
    reviews: 0,
    category: "headphones",
    colors: ["red", "black",],
    brand: "A63",
    isStock: true,
    overView: "Microphones",
    isNew: true,
    _base: cat.headphones,
  },
  {
    _id: 2010,
    name: "HEAD SET SN-1020 (BLUETOOTH)",
    images: [
      "https://i.postimg.cc/vZzP0SLV/HEAD-SET-SN-1020-BLUETOOTH.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 599,
    discountedPrice: 549,
    quantity: 1,
    rating: 4,
    reviews: 60,
    category: "Headphones & Speakers",
    colors: ["red", "blue", "black",],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Microphones",
    isNew: true,
    _base: cat.headphones,
  },
  {
    _id: 2011,
    name: "HEAD SET SY-750",
    images: [
      "https://i.postimg.cc/DZWByfVr/HEAD-SET-SY-750.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1749,
    discountedPrice: 1699,
    quantity: 1,
    rating: 4,
    reviews: 60,
    category: "headphones",
    colors: [ "black",],
    brand: "sy 750",
    isStock: true,
    overView: "Microphones",
    isNew: true,
    _base: cat.headphones,
  },
  {
    _id: 2012,
    name: "N191 laptop cooling Pad",
    images: [
      "https://i.postimg.cc/RZ9sQzfm/N191-laptop-cooling-Pad.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1499,
    discountedPrice: 0,
    quantity: 1,
    rating: 4.7,
    reviews: 0,
    category: "coolingPad",
    colors: ["black", ],
    brand: "N191 laptop cooling Pad",
    isStock: true,
    overView: "coolingPad",
    isNew: true,
    _base: cat?.coolingPad,
  },
  {
    _id: 2013,
    name: "N 99 LAPTOP COOLING PAD",
    images: [
      "https://i.postimg.cc/CLbrqKRJ/N-99-LAPTOP-COOLING-PAD.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 2299,
    discountedPrice: 0,
    quantity: 1,
    rating: 4.7,
    reviews: 0,
    category: "Power Tools",
    colors: [ "black",],
    brand: "N 99 LAPTOP COOLING PAD",
    isStock: true,
    overView: "coolingPad",
    isNew: true,
    _base: cat?.coolingPad,
  },
  {
    _id: 2014,
    name: "USB KEYBOARD BW-08",
    images: [
      "https://i.postimg.cc/xjztwd3Y/USB-KEYBOARD-BW-08.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 210,
    discountedPrice: 200,
    quantity: 1,
    rating: 3.9,
    reviews: 100,
    category: "key_bords",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "key_bords",
    isNew: true,
    _base: cat?.key_bords,
  },
  {
    _id: 2015,
    name: "X Brand English Keyboard TP308",
    images: [
      "https://i.postimg.cc/vBpX1RMp/X-Brand-English-Keyboard-TP308.png",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1200,
    discountedPrice: 0,
    quantity: 1,
    rating: 0,
    reviews: 0,
    category: "key_bords",
    colors: [ "black"],
    brand: "X brand",
    isStock: true,
    overView: "key_bords",
    isNew: true,
    _base: cat?.key_bords,
  },
  {
    _id: 2016,
    name: "USB Mini Key bord",
    images: [
      "https://i.postimg.cc/sxLf16dL/c35625c85b960787fd798e7855fac157.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1499,
    discountedPrice: 1449,
    quantity: 1,
    rating: 4.5,
    reviews: 0,
    category: "key_bords",
    colors: ["black"],
    brand: "View",
    isStock: true,
    overView: "key_bords",
    isNew: true,
    _base: cat?.key_bords,
  },
  {
    _id: 2017,
    name: "Jedel 3 language Keyboard K11",
    images: [
      "https://i.postimg.cc/2590Dbtj/Jedel-3-language-Keyboard-K11.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1099,
    discountedPrice: 1049,
    quantity: 1,
    rating: 5,
    reviews: 0,
    category: "key_bords",
    colors: ["black"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "key_bords",
    isNew: true,
    _base: cat?.key_bords,
  },
  {
    _id: 2018,
    name: "GAMING KEYBOARD & MOUSE ( KM99 )",
    images: [
      "https://i.postimg.cc/R0gDZbWB/GAMING-KEYBOARD-MOUSE-KM99.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 2100,
    discountedPrice: 2000,
    quantity: 1,
    rating: 3.9,
    reviews: 100,
    category: "key_bords",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "key_bords",
    isNew: true,
    _base: cat?.key_bords,
  },
  {
    _id: 2019,
    name: "Rainbow Wired Gaming Keyboard Mouse GTX360",
    images: [
      "https://i.postimg.cc/xC7pKJGp/Rainbow-Wired-Gaming-Keyboard-Mouse-GTX360.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 2100,
    discountedPrice: 2000,
    quantity: 1,
    rating: 3.9,
    reviews: 100,
    category: "key_bords",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "key_bords",
    isNew: true,
    _base: cat?.key_bords,
  },
  {
    _id: 2020,
    name: "Wireless Combo Keyboard Mouse",
    images: [
      "https://i.postimg.cc/yN1GBzYj/W500-Banda-2-4-GHz-Wireless-Combo-Keyboard-Mouse.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 2350,
    discountedPrice: 2300,
    quantity: 1,
    rating: 3.9,
    reviews: 100,
    category: "key_bords",
    colors: [ "black"],
    brand: "W500 Banda",
    isStock: true,
    overView: "key_bords",
    isNew: true,
    _base: cat?.key_bords,
  },
  {
    _id: 2021,
    name: "Shue",
    images: [
      "https://i.postimg.cc/637mtYcq/shoe.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 2999,
    discountedPrice: 2799,
    quantity: 1,
    rating: 3.9,
    reviews: 100,
    category: "shoes",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "shoess",
    isNew: true,
    _base: cat?.Shoes,
  },





//   {
//     _id: 2016,
//     name: "Sony PS4 Controller Bluetooth Vibration Gamepad For Playstation 4 Detroit Wireless Joystick For PS4 Games Consol",
//     images: [
//       "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
//       "https://i.ibb.co/m6ZN7LX/soundBox.webp",
//       "https://i.ibb.co/wdV3b9q/vaccum.webp",
//       "https://i.ibb.co/tcdSfrr/blueGun.jpg",
//       "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
//     ],
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
//     regularPrice: 80,
//     discountedPrice: 75,
//     quantity: 1,
//     rating: 4.2,
//     reviews: 110,
//     category: "Game and Video",
//     colors: ["red", "blue", "green", "yellow", "black", "white"],
//     brand: "Lorem ipsum dolor sit",
//     isStock: true,
//     overView: "Game & Video",
//     isNew: true,
//     _base: cat?.gameAndVideo,
//   },
//   {
//     _id: 2017,
//     name: "GSR 120-Li Hand Drill 12V Lithium Drill Household Power Tool Screwdriver With One Battery – GSR120-LI 1Battery",
//     images: [
//       "https://i.ibb.co/NxM3M4g/hand-Drill.jpg",
//       "https://i.ibb.co/m6ZN7LX/soundBox.webp",
//       "https://i.ibb.co/wdV3b9q/vaccum.webp",
//       "https://i.ibb.co/tcdSfrr/blueGun.jpg",
//       "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
//     ],
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
//     regularPrice: 560,
//     discountedPrice: 400,
//     quantity: 1,
//     rating: 4,
//     reviews: 300,
//     category: "Power Tools",
//     colors: ["red", "blue", "green", "yellow", "black", "white"],
//     brand: "Lorem ipsum dolor sit",
//     isStock: true,
//     overView: "Power Tools",
//     isNew: true,
//     _base: cat?.coolingPad,
//   },
//   {
//     _id: 2016,
//     name: "220 NORMAL MOUSE",
//     images: [
//       "https://i.postimg.cc/NjgD2kqf/JEDEL-220-NORMAL-MOUSE.jpgJEDEL",
//     ],
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
//     regularPrice: 250,
//     discountedPrice: 240,
//     quantity: 1,
//     rating: 4.2,
//     reviews: 110,
//     category: "TV and Audio",
//     colors: ["red", "blue", "green", "yellow", "black", "white"],
//     brand: "Lorem ipsum dolor sit",
//     isStock: true,
//     overView: "Blutooth Speakers",
//     isNew: true,
//     _base: cat?.mouse,
//   },
//   {
//     _id: 2017,
//     name: "Global Version Mi TV Stick Android TV 9.0 Smart 2K HDR 1GB RAM 8GB ROM Bluetooth 4.2 Mini TV Dongle",
//     images: [
//       "https://i.ibb.co/GvBj7SV/usb.jpg",
//       "https://i.ibb.co/m6ZN7LX/soundBox.webp",
//       "https://i.ibb.co/wdV3b9q/vaccum.webp",
//       "https://i.ibb.co/tcdSfrr/blueGun.jpg",
//       "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
//     ],
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
//     regularPrice: 60,
//     discountedPrice: 55,
//     quantity: 1,
//     rating: 4,
//     reviews: 100,
//     category: "TV Box",
//     colors: ["red", "blue", "green", "yellow", "black", "white"],
//     brand: "Lorem ipsum dolor sit",
//     isStock: true,
//     overView: "TV Box",
//     isNew: true,
//     _base: cat?.key_bords,
//   },
//   {
//     _id: 2018,
//     name: "Xiaomi Mijia LCD Writing Tablet With Pen 10 13.5inch Digital Drawing Message Graphics Electronic Handwriting Pad With Pen",
//     images: [
//       "https://i.ibb.co/fxJkDbC/writing-Tablet.webp",
//       "https://i.ibb.co/m6ZN7LX/soundBox.webp",
//       "https://i.ibb.co/wdV3b9q/vaccum.webp",
//       "https://i.ibb.co/tcdSfrr/blueGun.jpg",
//       "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
//     ],
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
//     regularPrice: 350,
//     discountedPrice: 330,
//     quantity: 1,
//     rating: 4.2,
//     reviews: 70,
//     category: "Tablets",
//     colors: ["red", "blue", "green", "yellow", "black", "white"],
//     brand: "Lorem ipsum dolor sit",
//     isStock: true,
//     overView: "Tablets",
//     isNew: true,
//     _base: cat?.tablets,
//   },
//   {
//     _id: 2019,
//     name: "New Creative Cloth Art Home Outdoors Bluetooth Sound Box",
//     images: [
//       "https://i.ibb.co/m6ZN7LX/soundBox.webp",
//       "https://i.ibb.co/m6ZN7LX/soundBox.webp",
//       "https://i.ibb.co/wdV3b9q/vaccum.webp",
//       "https://i.ibb.co/tcdSfrr/blueGun.jpg",
//       "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
//     ],
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
//     regularPrice: 120,
//     discountedPrice: 100,
//     quantity: 1,
//     rating: 4.1,
//     reviews: 20,
//     category: "Bluetooth Speakers",
//     colors: ["red", "blue", "green", "yellow", "black", "white"],
//     brand: "Lorem ipsum dolor sit",
//     isStock: true,
//     overView: "Bluetooth Speakers",
//     isNew: true,
//     _base: cat?.mouse,
//   },
//   {
//     _id: 2020,
//     name: "Global Version Redmi Note 9 Pro 6GB RAM 64GB ROM Smartphone Mobile Phone",
//     images: [
//       "https://i.ibb.co/WyvSw8N/phoneTwo.jpg",
//       "https://i.ibb.co/m6ZN7LX/soundBox.webp",
//       "https://i.ibb.co/wdV3b9q/vaccum.webp",
//       "https://i.ibb.co/tcdSfrr/blueGun.jpg",
//       "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
//     ],
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
//     regularPrice: 450,
//     discountedPrice: 410,
//     quantity: 1,
//     rating: 3.7,
//     reviews: 190,
//     category: "Cell Phones",
//     colors: ["red", "blue", "green", "yellow", "black", "white"],
//     brand: "Lorem ipsum dolor sit",
//     isStock: true,
//     overView: "Dual Sim Phones",
//     isNew: true,
//     _base: cat?.cellPhones,
//   },
//   {
//     _id: 2021,
//     name: "HEAD SET SN-1020 (BLUETOOTH)",
//     images: [
//       "https://i.postimg.cc/vZzP0SLV/HEAD-SET-SN-1020-BLUETOOTH.jpg",
//     ],
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
//     regularPrice: 350,
//     discountedPrice: 320,
//     quantity: 1,
//     rating: 3.9,
//     reviews: 10,
//     category: "Headphones",
//     colors: ["red", "blue", "green", "yellow", "black", "white"],
//     brand: "Lorem ipsum dolor sit",
//     isStock: true,
//     overView: "Fitness Headphones",
//     isNew: true,
//     _base: cat?.headphones,
//   },
//   {
//     _id: 2022,
//     name: "Roborock S7 Robot Vacuum Cleaner For Home Sonic Mopping Ultrasonic Carpet Clean Alexa Mop Lifting Upgrade For S5 Max",
//     images: [
//       "https://i.ibb.co/09ySKVm/vaccum-Cleaner.webp",
//       "https://i.ibb.co/m6ZN7LX/soundBox.webp",
//       "https://i.ibb.co/wdV3b9q/vaccum.webp",
//       "https://i.ibb.co/tcdSfrr/blueGun.jpg",
//       "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
//     ],
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
//     regularPrice: 250,
//     discountedPrice: 240,
//     quantity: 1,
//     rating: 4.2,
//     reviews: 100,
//     category: "Robot Clean",
//     colors: ["red", "blue", "green", "yellow", "black", "white"],
//     brand: "Lorem ipsum dolor sit",
//     isStock: true,
//     overView: "Robot Clean",
//     isNew: true,
//     _base: cat?.robotClean,
//   },
//   {
//     _id: 2023,
//     name: "Klipsch R-120SW Powerful Detailed Home Speaker – Unit",
//     images: [
//       "https://i.ibb.co/bR9LcZY/home-Speaker.webp",
//       "https://i.ibb.co/m6ZN7LX/soundBox.webp",
//       "https://i.ibb.co/wdV3b9q/vaccum.webp",
//       "https://i.ibb.co/tcdSfrr/blueGun.jpg",
//       "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
//     ],
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
//     regularPrice: 600,
//     discountedPrice: 580,
//     quantity: 1,
//     rating: 4.7,
//     reviews: 200,
//     category: "headphones",
//     colors: ["red", "blue", "green", "yellow", "black", "white"],
//     brand: "Lorem ipsum dolor sit",
//     isStock: true,
//     overView: "Bluetooth Speaker",
//     isNew: true,
//     _base: cat?.mouse,
//   },
//   {
//     _id: 2024,
//     name: "ZY418 Ultra-Thin Sport MP3 MP4 Music Player",
//     images: [
//       "https://i.ibb.co/f9GKwRd/mp3-Player.webp",
//       "https://i.ibb.co/m6ZN7LX/soundBox.webp",
//       "https://i.ibb.co/wdV3b9q/vaccum.webp",
//       "https://i.ibb.co/tcdSfrr/blueGun.jpg",
//       "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
//     ],
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
//     regularPrice: 80,
//     discountedPrice: 70,
//     quantity: 1,
//     rating: 4.2,
//     reviews: 60,
//     category: "headphones",
//     colors: ["red", "blue", "black"],
//     brand: "Lorem ipsum dolor sit",
//     isStock: true,
//     overView: "Microphones",
//     isNew: true,
//     _base: cat?.headphones,
//   },
//   {
//     _id: 2025,
//     name: "Xiaomi Mi Watch Lite GPS Bluetooth 5.1 Smart Watch Sports Fitness Heart Rate Monitor 1.4 Inch TFTLCD Screen 5 ATM Waterproof Mi Band",
//     images: [
//       "https://i.ibb.co/9hHGFnT/watchTwo.jpg",
//       "https://i.ibb.co/m6ZN7LX/soundBox.webp",
//       "https://i.ibb.co/wdV3b9q/vaccum.webp",
//       "https://i.ibb.co/tcdSfrr/blueGun.jpg",
//       "https://i.ibb.co/pw0fGmx/gaming-Controller.webp",
//     ],
//     description:
//       "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
//     regularPrice: 220,
//     discountedPrice: 210,
//     quantity: 1,
//     rating: 4.5,
//     reviews: 90,
//     category: "Smart Watches",
//     colors: ["red", "blue", "green", "yellow", "black", "white"],
//     brand: "Lorem ipsum dolor sit",
//     isStock: true,
//     overView: "Smart Health Watch",
//     isNew: true,
//     _base: cat?.smartWatches,
//   },
 ];
